---
title: "FMPH243B project2"
author: "Keren Hu"
date: "2024-02-01"
output:
  html_document: default
  word_document: default
---

```{r,message=FALSE}
# install.packages("./ADNIMERGE_0.0.1.tar.gz", repos = NULL, type = "source")
library(ADNIMERGE)
library(remotes)
library(palmerpenguins)
library(GGally)
library(tidyverse)
library(gbm)
library(caret)
library(car)
library(glmnet)
data(adnimerge)
```

```{r}
pid = unique(adnimerge$RID) # 2432 participants
# Data filtration
dat = adnimerge[adnimerge$DX.bl %in% c("LMCI","EMCI"), ]
dat = dat[!is.na(dat$AGE),]
# age between 55 and 90;
dat = dat[dat$AGE >= 55, ]
dat = dat[dat$AGE <= 90, ]
# M <= 36
dat = dat[dat$M <= 36,]
length(unique(dat$RID)) # 1109 participants

basedat = dat[dat$M == 0,] # baseline dataset with 1109 participants
```

# Description of data
```{r}
# Create outcome variable 
dat$cAD = ifelse(dat$DX == "Dementia", 1, 0)
cAD_id = unique(dat$RID[dat$cAD==1])

basedat$cAD = ifelse(basedat$RID %in% cAD_id, 1, 0)
table(basedat$cAD)

# Create a variable of subtype of MCI
basedat$typeMCI = ifelse(basedat$DX.bl=="EMCI", "E",
                         ifelse(basedat$DX.bl=="LMCI", "L", NA))

# Predictors
pred = c("AGE", "PTEDUCAT", "CDRSB.bl", "ADAS11.bl", "ADAS13.bl", "ADASQ4.bl", "MMSE.bl", "RAVLT.immediate.bl", "RAVLT.learning.bl", "RAVLT.forgetting.bl", "RAVLT.perc.forgetting.bl", "LDELTOTAL.bl", "DIGITSCOR.bl", "TRABSCOR.bl", "FAQ.bl", "PTGENDER", "typeMCI", "PTMARRY")

basedf = basedat[, c("cAD", pred)]

library(compareGroups)
# Demographic description
tab1 <- compareGroups(cAD ~ ., data = basedf)
restab <- createTable(tab1)
export2md(restab, caption = "Demographic characteristics of study participants")
```


# Pairsplot
```{r, warning=FALSE,message=FALSE}

ggpairs(basedf[,c(2:16)],columnLabels = c("AGE", "YR_EDU", "CDRSD","ADAS11","ADAS13","ADASQ4","MMSE","RAVLT-I","RAVLT-L","RAVLT-F","RAVLT-PF","LDT","DIGIT","TMTBT","FAQ")) + theme(axis.text.x = element_text(face = "italic", color = "black",size = 6, angle = 45), axis.text.y=(element_text(face = "italic", color = "black",size = 6, angle = 45)))

```


#Missingness
```{r}
library(tidyverse)
library(rstatix)
library(ggpubr)
missing_id<- which(is.na(basedf$DIGITSCOR.bl))
missing_data<- basedf[missing_id,]
no_missing_data<- basedf[-missing_id,]

table(missing_data$cAD)

table(no_missing_data$cAD)

```
# Maybe exclude DIGITSCOR first, and bring it back in the sensitivity analysis

## Split train/testing sets

```{r, message=FALSE, warning=FALSE}
#new df for analysis
set.seed(211)
basedf_1<- basedf[,-c(14)]

train<- basedf_1 %>%
  sample_frac(0.7)

test<- anti_join(basedf_1,train, by=NULL)
```

## Fit logistic regression & validation

```{r}
fit.logi <- glm(cAD ~ ., family = "binomial", data = train)
fit.logi.back <- step(fit.logi, direction = "backward")

## cross-validation

data.pred<- predict(fit.logi.back, newdata = test, type = "response")
class.pred <- ifelse(data.pred > 0.5, 1, 0)
class.act<- test$cAD

(conf.mat <- confusionMatrix(as.factor(class.pred),as.factor(class.act))) # 0.7877
```
